# atalhos no estilo macOS/QuickTime
WHEEL_UP        add volume 5
WHEEL_DOWN      add volume -5
MBTN_LEFT       cycle pause
RIGHT           seek 5
LEFT            seek -5
UP              seek 60
DOWN            seek -60
Ctrl+f          cycle fullscreen
f               cycle fullscreen
Ctrl+w          quit
j               cycle sub
k               cycle audio
