# Gerado por `workspace-style apply` a partir de workspaces.json.
# Edite o JSON ou use: workspace-style set ID "Nome" "#RRGGBB"

workspace = 1, bordersize:1, gapsin:5, gapsout:8, animation:slidefade 15%

windowrule {
    name = workspace-profile-1
    match {
        workspace = 1
    }
    border_color = rgba(0a84ffff) rgba(0a84ff38)
    rounding = 12
}

workspace = 2, bordersize:1, gapsin:5, gapsout:8, animation:slidefade 15%

windowrule {
    name = workspace-profile-2
    match {
        workspace = 2
    }
    border_color = rgba(8e8e93ff) rgba(8e8e9338)
    rounding = 12
}

workspace = 3, bordersize:1, gapsin:5, gapsout:8, animation:slidefade 15%

windowrule {
    name = workspace-profile-3
    match {
        workspace = 3
    }
    border_color = rgba(0a84ffff) rgba(0a84ff38)
    rounding = 12
}

workspace = 4, bordersize:1, gapsin:5, gapsout:8, animation:slidefade 15%

windowrule {
    name = workspace-profile-4
    match {
        workspace = 4
    }
    border_color = rgba(ac8e68ff) rgba(ac8e6838)
    rounding = 12
}

workspace = 5, bordersize:1, gapsin:5, gapsout:8, animation:slidefade 15%

windowrule {
    name = workspace-profile-5
    match {
        workspace = 5
    }
    border_color = rgba(ff453aff) rgba(ff453a38)
    rounding = 12
}
