font_family JetBrainsMono Nerd Font
font_size 12.0

enable_audio_bell no
confirm_os_window_close 0

background_opacity 0.90
dynamic_background_opacity yes
background_blur 20

shell fish
# Sousa Nebula
foreground #cdd6f4
background #11111b
cursor #cba6f7
cursor_text_color #11111b
selection_foreground #f8f8f2
selection_background #45475a
color0 #181825
color1 #f38ba8
color2 #a6e3a1
color3 #f9e2af
color4 #89b4fa
color5 #cba6f7
color6 #89dceb
color7 #cdd6f4
color8 #585b70
color9 #f38ba8
color10 #a6e3a1
color11 #f9e2af
color12 #89b4fa
color13 #cba6f7
color14 #94e2d5
color15 #f8f8f2

window_padding_width 10
tab_bar_style powerline
tab_powerline_style slanted
active_tab_foreground #11111b
active_tab_background #cba6f7
inactive_tab_foreground #cdd6f4
inactive_tab_background #3b4261
tab_bar_background #11111b
